"""added cart v2

Revision ID: 0e7f73122076
Revises: 81c40ffe80d1
Create Date: 2022-04-22 14:13:34.922745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e7f73122076'
down_revision = '81c40ffe80d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'cart')
    op.add_column('user', sa.Column('cart', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cart')
    op.add_column('product', sa.Column('cart', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
