"""empty message

Revision ID: 756c02dd8a3e
Revises: 0e7f73122076
Create Date: 2022-04-22 14:53:58.232294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '756c02dd8a3e'
down_revision = '0e7f73122076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cart1', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.drop_column('user', 'cart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cart', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('user', 'cart1')
    # ### end Alembic commands ###
