"""added cart

Revision ID: 81c40ffe80d1
Revises: d9ad41639821
Create Date: 2022-04-22 14:08:16.904929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81c40ffe80d1'
down_revision = 'd9ad41639821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('cart', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.alter_column('product', 'photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('product', 'cart')
    # ### end Alembic commands ###
