"""Initial migration

Revision ID: d2bf97c63b24
Revises: 
Create Date: 2022-04-15 01:34:41.580566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2bf97c63b24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('login', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_seller', sa.Boolean(), nullable=True),
    sa.Column('desription', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=80), nullable=True),
    sa.Column('payment_type', sa.String(length=120), nullable=True),
    sa.Column('total_spending', sa.Integer(), nullable=True),
    sa.Column('registered_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_enter', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('selled_count', sa.Integer(), nullable=True),
    sa.Column('active_products', sa.Integer(), nullable=True),
    sa.Column('total_income', sa.Integer(), nullable=True),
    sa.Column('open_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=180), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.Column('open_datetime', sa.DateTime(), nullable=False),
    sa.Column('selled_datetime', sa.DateTime(), nullable=True),
    sa.Column('is_selled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('seller')
    op.drop_table('user')
    # ### end Alembic commands ###
